### ISSUE TITLE
name or value matching constraints

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#13]
### Description

This issue is to discuss the need for an API to add matchers using the `name` and `value` properties of interactive message payloads. Currently, the module only supports matching on `callback_id`, `type`, and whether or not its the result of an unfurl. If this is a feature you are interested in, please share how you'd use it.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by gterras** [comment]
I think it would make things a little bit easier. Right now working on decent sized buttons branches, most of the actions needing specific treatment are just a switch case to a function returning a replacement. Having the ability to match for `name` and `value` would have made me using more actions.  In the end it's just convenience. By the way thank you for your work !

**Comment by aoberoi** [comment]
great, the next step would be to propose an API for this type of matching. i'm open to suggestions.

**Comment by shanedewael** [comment]
Name and value aren't reliable matching criterion for Block Kit messages. We may be able to rethink how something similar might look in a Block Kit world if there's still interest.
