### ISSUE TITLE
NPM repo shows 0.1.1 while build here is 0.1.0

### ISSUE THREAD

**Issue by grandlogic** [slackapi/node-slack-interactive-messages#3]
### Description
I not able to use the NPM repository. NPM is not able to find the 0.1.1 version. I had to build this 0.1.0 version from source and link it that way.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slack-events version:
node version:
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
thanks @grandlogic, we had some build issues with our initial releases, which at the moment are completely broken. i'll be fixing these with a 0.1.2 release momentarily.
