### ISSUE TITLE
Agent config for response_url requests

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#32]
### Description

If you wanted to send your requests through a proxy, this would be necessary.

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
https://github.com/slackapi/node-slack-sdk/issues/823
