### ISSUE TITLE
Reference docs improvements

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#41]
### Description

Capturing some of the shortcomings of the reference docs:

* [ ] `@external` reference links do not render. should probably file a bug with jsdoc2md/jsdoc-to-markdown.
* [ ] no output for `@enum` members, specifically `errorCodes` in `index.js`

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
https://github.com/slackapi/node-slack-sdk/issues/825
