### ISSUE TITLE
Unable to start server locally

### ISSUE THREAD

**Issue by prolificcoder** [slackapi/node-slack-interactive-messages#42]
### Description

Running npm start locally is giving TypeError

> /Users/smalugu/code/exp/node-slack-interactive-messages/examples/express-all-interactions/node_modules/@slack/interactive-messages/dist/adapter.js:200
>         throw error;
>         ^
> 
> TypeError: Type must be 'select' or 'button'
>     at validateActionConstraints (/Users/smalugu/code/exp/node-slack-interactive-messages/examples/express-all-interactions/node_modules/@slack/interactive-messages/dist/adapter.js:87:12)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [ ] enhancement (feature request)
- [x ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
@slack/interactive-messages version:
node version:
OS version(s):8.1.2

#### Steps to reproduce:

1.Clone the repo
2.npm install
3.set the env variables as the docs
4.npm start

#### Expected result:

server listening on port message

#### Actual result:

Error message /Users/smalugu/code/exp/node-slack-interactive-messages/examples/express-all-interactions/node_modules/@slack/interactive-messages/dist/adapter.js:200
        throw error;
        ^

TypeError: Type must be 'select' or 'button'
    at validateActionConstraints (/Users/smalugu/code/exp/node-slack-interactive-messages/examples/express-all-interactions/node_modules/@slack/interactive-messages/dist/adapter.js:87:12)

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
@prolificcoder sorry about this! the reason it failed is because we haven't released the latest `master` yet. i'll try to get that out ASAP. you should then be able to `npm install @slack/interactive-messages` again in the directory to get the code working.
