### ISSUE TITLE
Document limits to using `respond()`

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#43]
### Description

the total number of times it can be used is 5, and the server is authoritative about that. document what error is expected if the limit is exceeded.

explicitly document that this doesn't interact with other rate limits (Web API, Events API, RTM API).

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
Reopened at https://github.com/slackapi/node-slack-sdk/issues/828
