### ISSUE TITLE
Example app Glitch instructions, not great

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#46]
### Description

1. The `SLACK_ACCESS_TOKEN` variable is only available after install, but if you try to install the app in the order the instructions are presented, it will fail and say you need to add at least one scope.

2. In enabling interactive components, where do I get the "Glitch URL"? Its in the "Share" menu, but it would be nice to be explicit. Maybe give an example.

3. Where do I put the environment variables? If you know Glitch, you'll know its in `🗝.env`, but many users don't know Glitch. Also, if you're running locally, its not clear that you can put this in `.env`.

4. You need a description for the slash command.

5. `PORT` needs to be commented out in `.env`

6. In `package.json`, `@slack/interactive-messages` dependency version specifier should be set to `"^0.3.0"`

Maybe there should be 2 completely different sets of instructions for setup locally and on Glitch.

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by adamcohen** [comment]
Also, typo in the readme: `/interactive-exmaple dialog: Creates a dialog with a user menu`, should be `example` and not `exmaple`

**Comment by ErwinLengkeek** [comment]
I'd like to see these changes happen. The pull request has been open for quite some time now. Shall I make another PR that includes just the points mentioned in this issue?

**Comment by aoberoi** [comment]
@ErwinLengkeek we would very much appreciate that!

**Comment by shanedewael** [comment]
https://github.com/slackapi/node-slack-sdk/issues/827
