### ISSUE TITLE
Allow RegExp callback_id constraint matches to expose match results

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#47]
### Description

If the adapter is going to use a RegExp to match against the `callback_id`, it would be useful to be able to pick out the parts in a capture group so you don't have to once again parse the callback_id inside the handler.

This would probably look like:
*  Change the matching implementation from using `RegExp.test()` to [`RegExp.exec()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec)
*  Expose the return value to the handler function, somehow. Ideas:
  -  as another argument to the handler, `handler(payload, respond, matches)` where `matches` is the value
  -  inside an `ext` property of `payload`, so that in the future there is a dedicated namespace for new types of data to be exposed to the handler from. so, for example, you might find these results in `payload.ext.callbackIdMatches`.

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
Addressed by #138. If this seems like a mistake, please fell free to open a new issue [in this project's new repository](https://github.com/slackapi/node-slack-sdk).
