### ISSUE TITLE
Message Actions not propagating because of condition in callback matching

### ISSUE THREAD

**Issue by mcolyer** [slackapi/node-slack-interactive-messages#52]
### Description

The new recently announced message actions aren't supported https://api.slack.com/actions.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

###

I believe the part that's preventing them from working is the fact that their payloads don't include either `actions` or `submission` which [fails the validations](https://github.com/slackapi/node-slack-interactive-messages/blob/97a737e66f210a98fe65b5066ef08c18df4691ef/src/adapter.js#L402).

**Comment by aoberoi** [comment]
doh! this is definitely a bug, since we intended to support message actions on day 1! thanks for pointing it out @mcolyer.

**Comment by mcolyer** [comment]
Good to know, is it something you could get fixed and merged relatively
quickly?

**Comment by klawson23** [comment]
@aoberoi Any chance we can get pull request #56 merged? This issue of not having a handler action found by dispatch for message actions is affecting me as well.
