### ISSUE TITLE
Use an npmignore file to only publish the output of babel to npm

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#54]
### Description

Recently we ran into some security issues in another package because `npm publish` will tar any files in the project directory, even the ones that are git ignored. Since this wasn't clear until npm@6, we didn't notice that random local files were being uploaded into the package.

On top of security, this would decrease the package size significantly, which is a big win.

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
Fixed with v1.0.0 😸
