### ISSUE TITLE
Export a function to verify request signatures

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#82]
### Description

It would be useful to expose a function that verifies request signatures, even when not using the request handler. This functionality would duplicate the work in 
https://github.com/slackapi/node-slack-events-api/issues/70. We could implement this by extracting that into a shared dependency of both of these packages, but that’s not required. 

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue

**Comment by aoberoi** [comment]
Reference #79.

**Comment by shanedewael** [comment]
Reopened in https://github.com/slackapi/node-slack-sdk/issues/829
