### ISSUE TITLE
This project is moving to slackapi/node-slack-sdk

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#83]
As a part of the next version of the [Node Slack SDK](https://github.com/slackapi/node-slack-sdk), we'll be moving this package to live along side its siblings in a single repository.

This is great news, because many users of this package are already using the `WebClient`, `RTMClient`, or `IncomingWebhook` objects from the `@slack/client` package, so that means there will be one place to file issues, read documentation, and look for help.

Please note that the package itself, including its API, is not changing in any meaningful way. The code will live at a different URL, but the package on npm will still be `@slack/interactive-messages`. There are new packages that are being created from `@slack/client`, and we encourage you to migrate to them if you're already using that package. 

In order to complete the transition, we will be closing all open issues in this repo, and opening new ones to represent them at https://github.com/slackapi/node-slack-sdk/issues. We'll clearly leave links so that there's no lost context or history. You can expect this to happen as soon as v5.0.0 is complete, which we're targeting for early March 2019.

If you have any questions or concerns, please leave a comment in the [announcement issue](https://github.com/slackapi/node-slack-sdk/issues/689).

**Comment by shanedewael** [comment]
It moved 🎉
