### ISSUE TITLE
Allow request verification using req.rawBody

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-interactive-messages#91]
### Description

Some hosting platforms (like Firebase Cloud) always parse the request body, and create the `req.body` property for convenience. Unfortunately, this prevents this library from being able to verify requests. However, there's a convention of placing the unparsed (but buffered) body on the `req.rawBody` property instead.

Using `req.rawBody` as a fallback for `req.body` during verification would allow users to deploy code using this package to more hosting platforms.

This issue is analogous to [one from the `@slack/events-api` package](https://github.com/slackapi/node-slack-events-api/issues/85). The work can likely be cribbed from [this PR](https://github.com/slackapi/node-slack-events-api/pull/90).

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
@ErwinLengkeek, beat you to making this issue 😄

**Comment by ErwinLengkeek** [comment]
@aoberoi I forgot about making it 👎 
Did make a PR though.

**Comment by shanedewael** [comment]
https://github.com/slackapi/node-slack-sdk/issues/758
